apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 100-namespace.yaml
- 200-rbac.yaml
- 700-deployment.yaml

images:
- name: controller
  newName: ko://github.com/openshift-pipelines/multicluster-proxy
